name: Test Release Binary

on:
  workflow_dispatch:
  push:

jobs:
  nosqlbench-tests:
    name: NoSQLBench Tests (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker-compose
        id: compose
        run: |
          docker network create --driver nat --subnet=192.168.100.0/24 proxy
          docker-compose -f docker-compose-tests-windows.yml up --abort-on-container-exit --exit-code-from=nosqlbench