name: Test Release Binary

on:
  workflow_dispatch:
  push:

jobs:
  nosqlbench-tests:
    name: NoSQLBench Tests (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker-compose
        id: compose
        run: |
          # Set LCOW_SUPPORTED Variable to 1 for enabled
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
          # Enable Experimental Features in Dockerd daemon.conf
          $configfile = @"
          {
              "experimental": true
          }
          "@
          $configfile | Out-File -FilePath C:\ProgramData\docker\config\daemon.json -Encoding ascii -Force
          docker-compose -f docker-compose-tests-windows.yml up --abort-on-container-exit --exit-code-from=nosqlbench